[package]
name = "url_shortner_app"
version = "0.1.0"
edition = "2024"

[dependencies]
proto-definations-snip-sight = {git = "https://github.com/phanidharguttikonda0/SnipSight.git", tag = "v1.0.1", package = "proto-definations-snip-sight"}
tonic = "0.13.1" # is a gRPC implementation for rust
tokio = { version = "1.46.1", features = ["full"] }
sqlx = { version = "0.8.6", features = ["postgres", "runtime-tokio-rustls", "migrate"] }
tracing = "0.1.41" # making sure using the same version