[package]
name = "url_shortner_app"
version = "0.1.0"
edition = "2024"

[dependencies]
tonic = "0.13.1" # is a gRPC implementation for rust
prost = "0.13.1" # is a protoBuffer implementation for rust
tokio = { version = "1.46.1", features = ["full"] }
tonic-reflection = "0.13.1" # to read gRPC defination at run-time
prost-types = "0.13.1" # making sure using the same version

[build-dependencies]
tonic-build = "0.13.1"